version: '3.8'

services:
  postgresdatabase:
    image: postgres
    container_name: postgresdatabase
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - postgresdata:/var/lib/postgresql/data
volumes:
  postgresdata:
    external: true
